{% set name = "napari-workflow-inspector" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-workflow-inspector-{{ version }}.tar.gz
  sha256: 50314c57f71c451ff3c5c9ab8163506c589b30204b34e9dbff35f5d92ce81ad5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - matplotlib-base
    - napari-plugin-engine >=0.1.4
    - napari-tools-menu
    - napari-workflows
    - numpy
    - python >=3.7
    - networkx

test:
  imports:
    - napari_workflow_inspector
  commands:
    - pip list
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/haesleinhuepf/napari-workflow-inspector
  summary: Inspect relationships between napari-plugins in active workflows
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/napari
    - haesleinhuepf
